name: run script
on:
  pull_request_target
  
jobs:
  run_tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      run: |
          chmod +x ./actions/test.sh
          ./actions/test.sh
      shell: bash
      env: 
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_REPO: ${{ github.repository }}
        issue_url: ${{ github.event.pull_request.issue_url }}
        LABELS: en-cours
