name: set en-cours label
on:
  pull_request_target
  
jobs:
  label_issues_en_cours:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - run: gh issue edit "$issue_url" --add-label "$LABELS"   
        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          issue_url: ${{ github.event.pull_request.issue_url }}
          LABELS: en-cours
